### ISSUE TITLE
👷 Deploying to fireemoji.io

### ISSUE THREAD

**Issue by jernejk** [SSWConsulting/SSW.FireEmoji#28]
Cc: @adamcogan @Hona @bradystroud @tkapa @theixdev 

Hi team,

We got the domain and we should deploy the app! 🎇

### Tasks

- [ ] Add GitHub actions
- [ ] Setup secrets
- [ ] Deploy to Azure
- [ ] Setup the domain

### More Information

Contact @chrisschultzssw to update any domain details to link up Azure Web Static App with the domain.

Thanks!

**Comment by bradystroud** [comment]
cc: @Hona @Hona @theixdev @jernejk @tkapa @JackDevAU 
Update: As per our conversation, we have deployed to GitHub Pages temporarily until we have time to deploy to Azure permanently. 
Check it out https://fireemoji.io
