### ISSUE TITLE
✨ Add description, color, GitHub emoji and examples for gitmojis

### ISSUE THREAD

**Issue by jernejk** [SSWConsulting/SSW.FireEmoji#37]
Hi team,
  
### Pain

Right now the UI does not give us the name and description of the gitmoji. Ideally, we would also want to have a usage example of a gitmoji for a better context of the emoji.

### Suggested Solution

Move the predefined list of emojis into the core class library and add the information there.
Optionally, it can be stored in a file but each platform can load the file differently which can make this approach impractical.

Example data:

| Property | Value |
| Gitmoji |  ✨|
| Name | Feature |
| Description | Used for new features |
| GitHub emoji | : stars : |
| Color | Yellow |
| Example | Add logout button |

### Tasks

- [ ] Move Gitmoji list to the core library
- [ ] Add more data to it (use gitmoji.io to help you out with name and descriptions)
- [ ] Check with @jaydenalchin for colors
- [ ] Add 1 or more examples for better clarity on its usage

### Screenshots

![image](https://user-images.githubusercontent.com/5943653/153548762-6d70a20d-1af7-4669-b801-9bf293059d39.png)
**Figure:** Atm, there are no names or descriptions of the gitmojis.

Thanks!
