### ISSUE TITLE
✨Create the ML project to guess the appropriate emoji

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.FireEmoji#4]
Cc: @tkapa, @adamcogan, @bradystroud, @jaydenalchin 

Hi @jernejk,
 
### Pain

Currently we don't have an ML project to do any of our emoji guessing!

### Suggested Solution

Create a new ML Dotnet project within our solution. Use the .csv generated from #3 to start generating suggestions for appropriate emoji to use based on a provided sentence.

### Tasks

- [x] Create a new ML Dotnet project
- [x] Train the model based on the provided .csv data
- [x] Output consistently appropriate emoji based on given string input.

Thanks!

**Comment by jernejk** [comment]
I believe we mark this one as done. 😊
