### ISSUE TITLE
✨ Extensions: VS Code

### ISSUE THREAD

**Issue by jernejk** [SSWConsulting/SSW.FireEmoji#43]
Cc:

Hi  team,
  
### Pain
I'm splitting up original #8 into a separate issue specifically just for VS Code extension.

### Suggested Solution

Investigate, develop, test and publish VS Code extension.

### Tasks

- [ ] Investigate VS Code extensions
- [ ] Create VS Code extension
- [ ] Beta test the extension
- [ ] Prepare for full release
- [ ] Publish it to VS market store
- [ ] Should new release be published as GitHub artifact as well?
- [ ] Investigate VS market place publishing automation

### More Information

The latest version of the extension is currently at `releases/latest/vscode`.

### Screenshots

![image](https://user-images.githubusercontent.com/5943653/153778347-ffcc6fb5-a437-4465-9291-9cb34955946e.png)
**Figure:** Original usage video by @JackDevAU 

![image](https://user-images.githubusercontent.com/5943653/153778359-68dce347-bd4e-4eb1-aee5-721d5a5444c4.png)
**Figure:** Current installation process.

![image](https://user-images.githubusercontent.com/5943653/153778368-06fc9c20-0cab-4e4c-b096-2994b416d6df.png)
**Figure:** Latest animation for usage with updated icon.

Thanks!
