### ISSUE TITLE
✨Extensions: Visual Studio

### ISSUE THREAD

**Issue by jernejk** [SSWConsulting/SSW.FireEmoji#44]
Cc: @tkapa, @adamcogan, @JackDevAU, @matt-goldman, @Hona, @bradystroud, @theixdev 

Hi  team,
  
### Pain
I'm splitting up original #8 into a separate issue specifically just for the Visual Studio extension.

### Suggested Solution

Investigate, develop, test and publish Visual Studio extension.

### Tasks

- [ ] Investigate Visual Studio extensions
- [ ] CreateVisual Studio extension
- [ ] Allow developer to try it out
- [ ] Beta test the extension
- [ ] Prepare for full release
- [ ] Publish it to VS market store
- [ ] Should new release be published as GitHub artifact as well?
- [ ] Investigate VS market place publishing automation

Thanks!
