### ISSUE TITLE
✨ Extensions: Rider

### ISSUE THREAD

**Issue by jernejk** [SSWConsulting/SSW.FireEmoji#45]
Cc: @tkapa, @adamcogan, @JackDevAU, @matt-goldman, @Hona, @bradystroud, @theixdev 

Hi  team,
  
### Pain
JetBrains Rider has a good chunk of users at SSW and it would be great to add support for this IDE.

### Suggested Solution

Investigate, develop, test and publish Rider extension.

### Tasks

- [ ] Investigate Rider extensions
- [ ] Create Rider extension
- [ ] Allow developer to try it out
- [ ] Beta test the extension
- [ ] Prepare for full release
- [ ] Publish it to JetBrains market store
- [ ] Should new release be published as GitHub artifact as well?
- [ ] Investigate JetBrains market place publishing automation

Thanks!
