### ISSUE TITLE
✨ Update PWA title and favicon

### ISSUE THREAD

**Issue by jernejk** [SSWConsulting/SSW.FireEmoji#48]
Cc: @adamcogan @JackDevAU @Hona @theixdev @tkapa @bradystroud 

Hi team,
  
### Pain

If I pin the PWA app, I get a generic icon instead of FireEmoji.
The title of the app is **SSW.FireEmoji.WebApp**.

![image](https://user-images.githubusercontent.com/5943653/155445561-7bd99100-378a-4669-9225-0a96893f0d14.png)
**Figure:** We have a generic Blazor icon when adding FireEmoji to the desktop.

### Suggested Solution

We should use a proper title and favicon for the website and PWA.

### Tasks

- [ ] Update title to `SSW.FireEmoji 🔥`
- [ ] Create favicon images
- [ ] Make sure it works when pinned to the task bar

### Screenshots

![image](https://user-images.githubusercontent.com/5943653/155445805-c48a0348-7c68-429a-972d-16a2bdfd43c3.png)
**Figure:** We can install FireEmoji as an app.

![image](https://user-images.githubusercontent.com/5943653/155445895-fd93f957-17f6-4a60-8e92-01bf213c450d.png)
**Figure:** We can see it on Windows when searching for it in the Start menu.

![image](https://user-images.githubusercontent.com/5943653/155446026-3f75e80a-016f-42f0-9efd-f60e6475ed38.png)
**Figure:** And it works like an app.

Thanks!
