### ISSUE TITLE
✨Create a Blazor PWA that implements the ML model

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.FireEmoji#6]
Cc: @tkapa, @adamcogan, @bradystroud, @jaydenalchin 

Hi @jernejk,
  
### Pain
We need a Blazor application to start serving the model's suggestions to users.

### Suggested Solution
Create a new Blazor project that is able to consume the model and output the emoji suggestions based on user input.  

### Tasks

- [x] Create a new Blazor application
- [x] Consume the model
- [x] Interact with user input

Thanks!

**Comment by jernejk** [comment]
Closing the issue.
Any new features should be a separate GitHub issue.
