### ISSUE TITLE
✨Investigate VS 2022 / VS Code extensions

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.FireEmoji#8]
Cc: @jernejk, @bradystroud, @adamcogan, @jaydenalchin 

Hi @tkapa,
  
### Pain
It's awesome that we have our website and application, however a way to access FireEmoji directly from Visual Studio or VSCode as application extensions would be awesome.

### Suggested Solution
Investigate how to create Visual Studio and VSCode extensions, and implement FireEmoji's solution when typing commit messages.

### Tasks

- [ ] Investigate creating Visual Studio
- [x] Investigate creating VS Code extensions
- [x] ~~Create sub repositories for each extension (e.g. SSW.FireEmoji.VisualStudio, SSW.FireEmoji.VSCode)~~
- [ ] Implement Visual Studio extension
- [x] Implement VSCode extension
- [x] Add folder `extensions` where each extension will in their own folder

Thanks!

**UPDATE:** Added additional tasks.

**Comment by bradystroud** [comment]
After some investigation, it seems likely that it is possible to create a VSC extension that will add an emoji to the commit message field.

This line of code shows how it is possible to read and write to the commit message field
https://github.com/seatonjiang/gitmoji-vscode/blob/6ccfb25489b2684ba1cda01187f51f2ff5e020ee/src/extension.ts#L94

**Comment by JackDevAU** [comment]
cc: @jernejk 

Following your suggestion @bradystroud, I made a quick PoC using the node `child_process` to run call a cli version of FireEmoji. 
Not sure if this is the best idea... but its a start. 

![FireEmoji](https://user-images.githubusercontent.com/57518417/152156252-e857b6d1-faf1-4e70-b3cf-65db16fb78f0.gif)
**Figure: GIF showcasing the current idea**

**Comment by jernejk** [comment]
Can you add a pull request so that we can investigate if that is the right approach?
It looks good to me but if it's not the best, we can iterate on it. 😊

Also, we should see if we can show other suggestions and a button to fix the suggestion. (Currently just link to a new GitHub issue)

**Comment by jernejk** [comment]
@matt-goldman

**Comment by jernejk** [comment]
Closing the issue and moving the conversation to #43, #44 and #45.
